language: node_js
node_js: 
  - stable

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database socialnetwork;' -U postgres

script: true

notifications:
  email: false